# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/Cellar/cmake/3.28.3/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/Cellar/cmake/3.28.3/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/Users/I569113/Downloads/Fiverr Currency Converter"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/Users/I569113/Downloads/Fiverr Currency Converter"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/Cellar/cmake/3.28.3/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/Cellar/cmake/3.28.3/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/opt/homebrew/Cellar/cmake/3.28.3/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/opt/homebrew/Cellar/cmake/3.28.3/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/opt/homebrew/Cellar/cmake/3.28.3/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/opt/homebrew/Cellar/cmake/3.28.3/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/opt/homebrew/Cellar/cmake/3.28.3/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/opt/homebrew/Cellar/cmake/3.28.3/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/Users/I569113/Downloads/Fiverr Currency Converter/CMakeFiles" "/Users/I569113/Downloads/Fiverr Currency Converter//CMakeFiles/progress.marks"
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/Users/I569113/Downloads/Fiverr Currency Converter/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named CurrencyConverter

# Build rule for target.
CurrencyConverter: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 CurrencyConverter
.PHONY : CurrencyConverter

# fast build rule for target.
CurrencyConverter/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CurrencyConverter.dir/build.make CMakeFiles/CurrencyConverter.dir/build
.PHONY : CurrencyConverter/fast

#=============================================================================
# Target rules for targets named CurrencyConverter_autogen_timestamp_deps

# Build rule for target.
CurrencyConverter_autogen_timestamp_deps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 CurrencyConverter_autogen_timestamp_deps
.PHONY : CurrencyConverter_autogen_timestamp_deps

# fast build rule for target.
CurrencyConverter_autogen_timestamp_deps/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CurrencyConverter_autogen_timestamp_deps.dir/build.make CMakeFiles/CurrencyConverter_autogen_timestamp_deps.dir/build
.PHONY : CurrencyConverter_autogen_timestamp_deps/fast

#=============================================================================
# Target rules for targets named CurrencyConverter_autogen

# Build rule for target.
CurrencyConverter_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 CurrencyConverter_autogen
.PHONY : CurrencyConverter_autogen

# fast build rule for target.
CurrencyConverter_autogen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CurrencyConverter_autogen.dir/build.make CMakeFiles/CurrencyConverter_autogen.dir/build
.PHONY : CurrencyConverter_autogen/fast

CurrencyConverter_autogen/mocs_compilation.o: CurrencyConverter_autogen/mocs_compilation.cpp.o
.PHONY : CurrencyConverter_autogen/mocs_compilation.o

# target to build an object file
CurrencyConverter_autogen/mocs_compilation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CurrencyConverter.dir/build.make CMakeFiles/CurrencyConverter.dir/CurrencyConverter_autogen/mocs_compilation.cpp.o
.PHONY : CurrencyConverter_autogen/mocs_compilation.cpp.o

CurrencyConverter_autogen/mocs_compilation.i: CurrencyConverter_autogen/mocs_compilation.cpp.i
.PHONY : CurrencyConverter_autogen/mocs_compilation.i

# target to preprocess a source file
CurrencyConverter_autogen/mocs_compilation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CurrencyConverter.dir/build.make CMakeFiles/CurrencyConverter.dir/CurrencyConverter_autogen/mocs_compilation.cpp.i
.PHONY : CurrencyConverter_autogen/mocs_compilation.cpp.i

CurrencyConverter_autogen/mocs_compilation.s: CurrencyConverter_autogen/mocs_compilation.cpp.s
.PHONY : CurrencyConverter_autogen/mocs_compilation.s

# target to generate assembly for a file
CurrencyConverter_autogen/mocs_compilation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CurrencyConverter.dir/build.make CMakeFiles/CurrencyConverter.dir/CurrencyConverter_autogen/mocs_compilation.cpp.s
.PHONY : CurrencyConverter_autogen/mocs_compilation.cpp.s

converter.o: converter.cpp.o
.PHONY : converter.o

# target to build an object file
converter.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CurrencyConverter.dir/build.make CMakeFiles/CurrencyConverter.dir/converter.cpp.o
.PHONY : converter.cpp.o

converter.i: converter.cpp.i
.PHONY : converter.i

# target to preprocess a source file
converter.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CurrencyConverter.dir/build.make CMakeFiles/CurrencyConverter.dir/converter.cpp.i
.PHONY : converter.cpp.i

converter.s: converter.cpp.s
.PHONY : converter.s

# target to generate assembly for a file
converter.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CurrencyConverter.dir/build.make CMakeFiles/CurrencyConverter.dir/converter.cpp.s
.PHONY : converter.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CurrencyConverter.dir/build.make CMakeFiles/CurrencyConverter.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CurrencyConverter.dir/build.make CMakeFiles/CurrencyConverter.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CurrencyConverter.dir/build.make CMakeFiles/CurrencyConverter.dir/main.cpp.s
.PHONY : main.cpp.s

mainwindow.o: mainwindow.cpp.o
.PHONY : mainwindow.o

# target to build an object file
mainwindow.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CurrencyConverter.dir/build.make CMakeFiles/CurrencyConverter.dir/mainwindow.cpp.o
.PHONY : mainwindow.cpp.o

mainwindow.i: mainwindow.cpp.i
.PHONY : mainwindow.i

# target to preprocess a source file
mainwindow.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CurrencyConverter.dir/build.make CMakeFiles/CurrencyConverter.dir/mainwindow.cpp.i
.PHONY : mainwindow.cpp.i

mainwindow.s: mainwindow.cpp.s
.PHONY : mainwindow.s

# target to generate assembly for a file
mainwindow.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CurrencyConverter.dir/build.make CMakeFiles/CurrencyConverter.dir/mainwindow.cpp.s
.PHONY : mainwindow.cpp.s

plotwidget.o: plotwidget.cpp.o
.PHONY : plotwidget.o

# target to build an object file
plotwidget.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CurrencyConverter.dir/build.make CMakeFiles/CurrencyConverter.dir/plotwidget.cpp.o
.PHONY : plotwidget.cpp.o

plotwidget.i: plotwidget.cpp.i
.PHONY : plotwidget.i

# target to preprocess a source file
plotwidget.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CurrencyConverter.dir/build.make CMakeFiles/CurrencyConverter.dir/plotwidget.cpp.i
.PHONY : plotwidget.cpp.i

plotwidget.s: plotwidget.cpp.s
.PHONY : plotwidget.s

# target to generate assembly for a file
plotwidget.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CurrencyConverter.dir/build.make CMakeFiles/CurrencyConverter.dir/plotwidget.cpp.s
.PHONY : plotwidget.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... CurrencyConverter_autogen"
	@echo "... CurrencyConverter_autogen_timestamp_deps"
	@echo "... CurrencyConverter"
	@echo "... CurrencyConverter_autogen/mocs_compilation.o"
	@echo "... CurrencyConverter_autogen/mocs_compilation.i"
	@echo "... CurrencyConverter_autogen/mocs_compilation.s"
	@echo "... converter.o"
	@echo "... converter.i"
	@echo "... converter.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... mainwindow.o"
	@echo "... mainwindow.i"
	@echo "... mainwindow.s"
	@echo "... plotwidget.o"
	@echo "... plotwidget.i"
	@echo "... plotwidget.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

